### ISSUE TITLE
Error decrypting

### ISSUE THREAD

**Issue by evandrojr** [onmodulus/file-encryptor#2]
Hi!

I am getting this error when I try to decrypt a file. I am using your example. Any help will be appreciated.

Thanks!

crypto.js:292
  var ret = this._binding.final();
                          ^
TypeError: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipher.Cipher.final (crypto.js:292:27)
    at ReadStream.<anonymous> (/home/j/lab/node_modules/file-encryptor/lib/file-encryptor.js:57:33)
    at ReadStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by tzmanics** [comment]
Hi @evandrojr sorry for the big delay, let us know if you are still working on this issue or have any other questions. For now I'm going to close this issue but please feel free to re-open. Thanks!
