### ISSUE TITLE
Can not decrypt

### ISSUE THREAD

**Issue by Liberateur** [onmodulus/file-encryptor#9]
Same problem here : https://github.com/XervoIO/file-encryptor/issues/6

Hey hi, I have a problem to decrypt my archive. The archive works normally.

CODE :

```
// Get modules
const fs    = require('fs');
const crypt = require('file-encryptor');

// Set key
const key = '256_CHARACTERS_UTF8';

// Encrypt archive
crypt.encryptFile('my_archive_3MB.tar.gz', 'my_archive_3MB.tar.gz.crypt', key, { algorithm: 'aes256' }, (err)=>
{
	// Decrypt archive
	crypt.decryptFile('my_archive_3MB.tar.gz.crypt', 'my_archive_3MB.tar.gz', key, { algorithm: 'aes256' }, (err)=>
	{
		console.log(err);
	});
});
```

EXECUTE FILE IN CONSOLE :

```
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipher.final (crypto.js:158:26)
    at ReadStream.<anonymous> (/Users/cedric/Developer/research/kordacloud/backuper/node_modules/file-encryptor/lib/file-encryptor.js:63:35)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:7968) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by scottie** [comment]
Issue is cause your key is invalid, due to padding.
Here is fix: 
https://github.com/XervoIO/file-encryptor/pull/13

**Comment by AndrWeisR** [comment]
> 
> 
> Issue is cause your key is invalid, due to padding.
> Here is fix:
> #13

For me, I don't get the "wrong final block length" error in any case.
But when I add this autopadding fix, it causes the file to not be decrypted in its entirety for me. The last few characters of the file are missing.
